### ISSUE TITLE
Server README.md Setup steps are not sufficient

### ISSUE THREAD

**Issue by srnec** [ERNICommunity/ErniEventManager#44]
### AS IS:
After applying all the mentioned steps in **README.md** file under **Setup** chapter it won't start the server successfully after executing `npm run watch`. This is caused by missing environment variables:

- MONGO_SERVER - by default in our case 'mongodb://localhost:27017'
- MONGO_DATABASE = by default in our case 'admin'

These variables are obviously mandatory since `migrations/config.js` and `Database.ts` are dependent on these variables.

### TO BE:
We should think about how to fix this. 
Possibilities: 

1. Create a script that has to be run by developer which will execute and set everything needed
2. Update README.md with step to tell developer not to forget to create these env. variables

The main benefit is that any new participant in this project doesn't need to debug or investigate why it didn't run after doing all steps from README.md file.

**PS:**
Maybe it would be beneficial to extend the 

> Add SSH private key to /key/private.key for authorization

step into more detailed steps (RSA 2048bits exported as OpenSSH key, e.g. via PuTTYGen)

**Comment by rochus222** [comment]
private key was removed in #70 
I updated .env-example and README.MD file
I think that is enough
