### ISSUE TITLE
Unexpected formatting of dates during event editing

### ISSUE THREAD

**Issue by srnec** [ERNICommunity/ErniEventManager#45]
### AS IS:
After an event is created (with non-default start & end dates) and is edited the start & end date fields display string representation of ISO-8601 format.

![image](https://user-images.githubusercontent.com/6944943/45000894-d237ea80-afc8-11e8-99b1-f6a877cbd1ca.png)

### TO BE:
It should display dd.mm.yyyy or dd.mm.yyyy hh:mm (it can be formatted based on users locale)

**Comment by waaana** [comment]
Not needed, will be reworked
