### ISSUE TITLE
Events edit view is too narrow

### ISSUE THREAD

**Issue by rochus222** [ERNICommunity/ErniEventManager#66]
When implementing #53 I realized that displayed data are too narrow and do not go with set col-12 width. I was testing it on Chrome. Can somebody reproduce this issue? 

![image](https://user-images.githubusercontent.com/5399412/48947452-8777a000-ef31-11e8-951b-39d6b759359b.png)

**Comment by srnec** [comment]
I thought I created issue for this... I already saw it in the past but apparently forgot to report as issue.
